# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 1
sudo: false
language: node_js
node_js:
  - "10"
  - "8"

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set loglevel warn
  - npm install --global npm@latest

script:
  - npm run bootstrap
  - npm run test

notifications:
  slack: dev-thought:l0uEtx7EgJs2lQsaeINfVEk1